const express = require('express')
const userController = require('../controllers/userController')
const cartController = require('../controllers/cartController')
const orderController = require('../controllers/orderController')
const wishlistController = require('../controllers/wishlistController')
const couponController = require('../controllers/couponController')
const walletController = require('../controllers/walletController')
const router = express()
const userware = require('../middleware/userware')
router.set('view engine','ejs')
// router.set('views','/views/user')

router.get('/',userware.userLogout,userController.getL)
router.get('/login',userware.userLogout,userController.getLogin)
router.post('/login',userware.userLogout,userController.postLogin)

router.get('/logout',userware.userLogin,userController.logout)

router.get('/signup',userware.userLogout,userController.getsignup)
router.post('/signup',userController.postsignup)

router.get('/otp',userware.userLogout,userController.getOtp)
router.post('/otp',userController.postOtp)
router.post('/resendotp',userware.userLogout,userController.postResend)

router.get('/home',userController.getHome)
router.get('/home/category',userware.userLogin,userController.categoryFilter)
router.get('/profile',userware.userLogin,userController.getProfile)
router.get('/addAddress',userware.userLogin,userController.getAddAddress)
router.post('/addAddress',userware.userLogin,userController.postAddAddress)
router.get('/addresses',userware.userLogin,userController.getAddress)
router.get('/addresses/edit',userware.userLogin,userController.getEditAddress)
router.put('/addresses/edit',userware.userLogin,userController.putEditAddress)
router.get('/addresses/del/',userware.userLogin,userController.getDelAddress)
router.get('/orders',userware.userLogin,orderController.getOrders)
router.get('/orders/orderDetails',userware.userLogin,orderController.getOrderDetails)
router.get('/order/cancelOrder',userware.userLogin,orderController.cancelOrder)
router.get('/order/returnOrder',userware.userLogin,orderController.returnOrder)
router.get('/profile/change-password',userware.userLogin,userController.changePassword)
router.put('/profile/change-password',userware.userLogin,userController.putChangePassword)

router.get('/cart',userware.userLogin,cartController.getCart)
router.post('/addToCart',userware.userLogin,cartController.postAddToCart)
router.get('/cart/deleteItem',userware.userLogin,cartController.deleteItem)
router.post('/increment',userware.userLogin,cartController.incCart)
router.post('/decrement',userware.userLogin,cartController.decCart)

router.get('/wallet',userware.userLogin,walletController.wallet)
router.get('/wishlist',userware.userLogin,wishlistController.wishlist)
router.post('/saveToWishlist',userware.userLogin,wishlistController.saveToWishlist)
router.post('/moveToCart',userware.userLogin,wishlistController.moveToCart)
router.post('/removeFromWishlist',userware.userLogin,wishlistController.remove)

router.post('/couponRemove',userware.userLogin,couponController.couponRemove)
router.post('/couponApply',userware.userLogin,couponController.couponApply)
router.get('/checkout',userware.userLogin,cartController.getCheckout)
router.post('/createOrder',userware.userLogin,orderController.createOrder)
router.post('/verify-payment',userware.userLogin,orderController.verify_Payment)
router.get('/orderPlaced',userware.userLogin,orderController.orderPlaced)

router.get('/productDetails',userware.userLogin,userController.productDetails)

module.exports = router;